# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'ITMSTesterAdvanceAutomation' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  def wait_for_window(self, timeout = 2):
    sleep(round(timeout / 1000))
    wh_now = @driver.window_handles
    wh_then = @vars['window_handles']
    wh_now.find { |window| window != wh_then.first
  end
  it 'iTMSTesterAdvanceAutomation' do
    @driver.get('https://itmscoaching.herokuapp.com/switch-window')
    @driver.manage.resize_to(1382, 744)
    @vars['window_handles'] = @driver.window_handles
    @driver.find_element(:id, 'new-tab-button').click
    @vars['win3314'] = wait_for_window(2000)
    @vars['root'] = @driver.window_handle
    @driver.switch_to.window(@vars['win3314'])
    @driver.switch_to.window(@vars['root'])
    @driver.find_element(:id, 'alert-button').click
    expect(@driver.switch_to.alert.text).to eq('This is a test alert!')
  end
end
