# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'ITMSTesterAdvanceAutomation' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'iTMSTesterAdvanceAutomation' do
    @driver.get('http://automationpractice.com/index.php')
    @driver.manage.resize_to(1382, 744)
    @driver.find_element(:link_text, 'Sign in').click
    @driver.find_element(:css, '#SubmitLogin > span').click
    expect(@driver.title).to eq('Login - My Store')
  end
end
