# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'ITMSTesteradvanceAutomationside' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'iTMSTesteradvanceAutomationside' do
    @driver.get('http://www.practiceselenium.com/practice-form.html')
    @driver.manage.resize_to(1382, 744)
    @driver.find_element(:css, '.control-group:nth-child(4) > p:nth-child(1)').click
    @driver.find_element(:name, 'firstname').click
    @driver.find_element(:name, 'firstname').send_keys('ITMS')
    @driver.find_element(:name, 'lastname').click
    @driver.find_element(:name, 'lastname').send_keys('Coaching')
    @driver.find_element(:css, '.inline').click
    @driver.find_element(:id, 'tea3').click
    @driver.find_element(:id, 'tea2').click
    @driver.find_element(:id, 'tool-1').click
    @driver.find_element(:id, 'continents').click
    dropdown = @driver.find_element(:id, 'continents')
    dropdown.find_element(:xpath, "//option[. = 'Asia']").click
    @driver.find_element(:id, 'continents').click
    dropdown = @driver.find_element(:id, 'selenium_commands')
    dropdown.find_element(:xpath, "//option[. = 'Browser Commands']").click
    dropdown = @driver.find_element(:id, 'selenium_commands')
    dropdown.find_element(:xpath, "//option[. = 'Browser Commands']").click
    dropdown = @driver.find_element(:id, 'selenium_commands')
    dropdown.find_element(:xpath, "//option[. = 'Wait Commands']").click
    @driver.find_element(:id, 'submit').click
    expect(@driver.title).to eq('Welcome')
  end
end
